# Generated by Django 5.2.4 on 2025-08-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='ژانر')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانر ها',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام فیلم')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='پوستر')),
                ('showtime', models.DateTimeField(verbose_name='زمان نمایش')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('short_description', models.TextField(null=True, verbose_name='توضیحات کوتاه')),
                ('gener', models.ManyToManyField(to='booking_module.gener', verbose_name='ژانر')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم ها',
            },
        ),
    ]
