# Generated by Django 5.2.4 on 2025-08-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_module', '0003_movie_expire_at_alter_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', null=True, verbose_name='عنوان در url'),
        ),
    ]
