# Generated by Django 5.2.5 on 2025-08-30 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_module', '0005_alter_movie_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام سالن')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت سالن')),
            ],
            options={
                'verbose_name': 'سالن',
                'verbose_name_plural': 'سالن ها',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='showtime',
        ),
        migrations.CreateModel(
            name='ShowTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='زمان نمایش')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_module.cinemahall', verbose_name='سالن')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_module.movie', verbose_name='فیلم')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس ها',
            },
        ),
    ]
