# Generated by Django 5.2.5 on 2025-08-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_module', '0006_cinemahall_remove_movie_showtime_showtimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gener',
            name='url_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان در url'),
        ),
    ]
