# Generated by Django 5.2.5 on 2025-09-05 12:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_module', '0007_gener_url_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='showtimes',
            name='parice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت'),
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=20, verbose_name='شماره صندلی')),
                ('extra_charge', models.IntegerField(default=0, verbose_name='هزینه اضافی صندلی')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_module.cinemahall', verbose_name='سالن')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_module.showtimes', verbose_name='زمان نمایش')),
            ],
            options={
                'verbose_name': 'صندلی',
                'verbose_name_plural': 'صندلی ها',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='قیمت ثبت شده')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_module.cinemahall', verbose_name='سالن')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_module.movie', verbose_name='فیلم')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking_module.seats', verbose_name='صندلی')),
                ('time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_module.showtimes', verbose_name='زمان نمایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط ها',
            },
        ),
        migrations.AddConstraint(
            model_name='seats',
            constraint=models.UniqueConstraint(fields=('seat_number', 'hall', 'time'), name='unique_seat'),
        ),
    ]
